### ISSUE TITLE
 Publishing linux egg files is problematic

### ISSUE THREAD

**Issue by behackett** [02strich/pykerberos#11]
Since version 1.1.8 a generic linux binary egg has been distributed through pypi. I'm guessing this is to help users that won't or can't install a compiler. Unfortunately this causes problems for users of easy-install that don't have the same "python 2.7" used to build the egg.

For example, when installing pykerberos for pypy easy_install grabs the egg file:

```
$ ./bin/pypy -m easy_install pykerberos
Searching for pykerberos
Reading https://pypi.python.org/simple/pykerberos/
Best match: pykerberos 1.1.9
Downloading https://pypi.python.org/packages/2.7/p/pykerberos/pykerberos-1.1.9-py2.7-linux-x86_64.egg#md5=4e6672337f0420c6964de0319566decf
Processing pykerberos-1.1.9-py2.7-linux-x86_64.egg
...
```

The installation completes without issue, but the interpreter faults when importing kerberos:

```
./bin/pypy
Python 2.7.10 (f3ad1e1e1d6215e20d34bb65ab85ff9188c9f559, Sep 01 2015, 11:00:11)
[PyPy 2.6.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import kerberos
Fatal Python error: PyThreadState_Get: no current thread
Aborted
```
Reinstalling with pip avoids the problem since pip does not support egg packages and builds the project from source:

```
./bin/pypy -m pip install pykerberos
Collecting pykerberos
  Downloading pykerberos-1.1.9.tar.gz
Building wheels for collected packages: pykerberos
  Running setup.py bdist_wheel for pykerberos
...

$ ./bin/pypy 
Python 2.7.10 (f3ad1e1e1d6215e20d34bb65ab85ff9188c9f559, Sep 01 2015, 11:00:11)
[PyPy 2.6.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import kerberos
```

There is nothing you can do to solve this problem in pykerberos. I would suggest removing the egg packages from pypi to avoid problems for future users. Also, note that pypi disallows uploading generic wheel binaries to avoid this exact problem. See the note here:

https://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#platform-wheels

**Comment by 02strich** [comment]
Thank you for raising this. The eggs have been removed from PyPi and no new ones will be published.

**Comment by behackett** [comment]
Thanks! I hope one day wheels can solve this problem.

**Comment by behackett** [comment]
FYI - https://www.python.org/dev/peps/pep-0513/
