### ISSUE TITLE
popenargs not defined

### ISSUE THREAD

**Issue by louahola** [02strich/pykerberos#13]
I'm getting the following error when trying to do an install on a fresh Ubuntu 14.04LTS:

File "/tmp/pip-build-GBpVfq/pykerberos/setup.py", line 37, in check_krb5_config
        cmd = popenargs[0]
    NameError: global name 'popenargs' is not defined

It looks like https://github.com/02strich/pykerberos/commit/6042a5e1c18f5cd13c4dc8afb9f525fe7de1d495 may have not cleaned up all the references to that variable.

**Comment by louahola** [comment]
I was able to move passed this error by installing the `libkrb5-dev` package.

**Comment by 02strich** [comment]
Thanks for raising this. I think I have fixed the issue in master.
