### ISSUE TITLE
Does pykerberos support windows?

### ISSUE THREAD

**Issue by apli** [02strich/pykerberos#18]

**Comment by 02strich** [comment]
There are people using it on Windows, but have not verified it's working on Windows. Long story short, yes it should

**Comment by ajdavis** [comment]
Consider also WinKerberos, a drop-in replacement specifically for Windows:

https://github.com/mongodb-labs/winkerberos

It's not on PyPI yet while Bernie waits for feedback. I'm sure he'd be interested to hear if it works for you.

**Comment by apli** [comment]
I tried to install it on windows, but failed for some compile problems.Seem lack of some dependencies,like krb5-config and some head files.
In short, the installation don't works well on windows. @02strich

**Comment by apli** [comment]
WinKerberos works! @ajdavis

**Comment by behackett** [comment]
@apli please let us know if you run into any issues with winkerberos. I plan to release it to pypi soon. Thanks!

**Comment by behackett** [comment]
WinKerberos is available on pypi - https://pypi.python.org/pypi/winkerberos
