### ISSUE TITLE
authGSSClientClean should not be deprecated

### ISSUE THREAD

**Issue by behackett** [02strich/pykerberos#19]
I think having the context object automatically destroy itself is a great idea. I did the same thing in WinKerberos. But this project has to remain compatible Apple's original kerberos module, which is shipped by linux distros like RHEL. To remain compatible you can't remove authGSSClientClean and the warning is raised in applications designed to work with any of the python kerberos work-alikes currently in existence (PyMongo being the example I maintain).

Instead, just document that using the function isn't necessary, since it no longer does anything, and remove the warning.

**Comment by 02strich** [comment]
To make sure I understand this correctly: you are encountering issues with the PyErr_WarnEx in authGSSClientClean?

**Comment by behackett** [comment]
There is no bug here. My concern is that if you remove authGSSClientClean your fork will become incompatible with Apple's version. Apple's version ships with Red Hat Enterprise Linux and a number of other distros so I have to continue to support it in PyMongo. How can I support both your fork and Apple's original project when Apple's project requires the use of authGSSClientClean?

**Comment by 02strich** [comment]
Thanks for the details, now I understand. I am not planning to remove authGSSClientClean for this exact reason, but stick to the current deprecation marker. Does this work for you?

**Comment by behackett** [comment]
Well, if you're not going to remove it why raise the deprecation warning? My concern is that users will see the warning in applications that use PyMongo with GSSAPI authentication and open bug reports in response.

I followed your lead when writing WinKerberos. Having the context object destroy itself was a great idea. But I just documented that the function exists for compatibility and does nothing. I don't raise a warning about it. 

https://github.com/mongodb-labs/winkerberos/blob/master/src/winkerberos.c#L320-L336

**Comment by 02strich** [comment]
Thanks for the great feedback, I now understand and have to agree - I did not consider this when adding the deprecation warning. I have updated in my latest commit to align with your approach, thanks for the feedback and pointers.

**Comment by behackett** [comment]
Looks good to me. Thanks!

**Comment by 02strich** [comment]
Thanks for the feedback. The change has been released as part of 1.1.12
