### ISSUE TITLE
"No such file or directory" for unknown reason

### ISSUE THREAD

**Issue by karyon** [02strich/pykerberos#24]
Hi :)

I'm getting this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django_auth_kerberos/backends.py", line 51, in check_password
    kerberos.checkPassword(username.lower(), password, getattr(settings, "KRB5_SERVICE", ""), settings.KRB5_REALM)
kerberos.BasicAuthError: ('No such file or directory', 2)

```

1.1.5 runs fine, 1.1.6 has the error from #12 which is fixed in 1.1.10, which shows this error here. KRB5_SERVICE is empty, but, as i said, 1.1.5 runs fine.

**Comment by karyon** [comment]
it does work when setting the verify_kdc parameter to false. i checked and the system does not seem to have a keytab file, maybe that's the reason. still, a more helpful error message would have been nice :)

**Comment by 02strich** [comment]
The error message comes up from the Kerberos library as part of the text for error code 2. The missing keytab or a similar missing file might very much be the reason for the error

**Comment by 02strich** [comment]
I would argue that changing this in the kerberos binding is the wrong layer (as the binding should try to be faithful to the underlying library). As this is nevertheless confusing, I have created https://github.com/02strich/django-auth-kerberos/issues/11 to improve this in the Django module.

**Comment by fhwedel-hoe** [comment]
I recently stumbled across this issue.

Ubuntu 18.04 provides pykerberos version 1.1.14 in the package python3-kerberos. Version 1.3.0 can be installed via pip3. 1.3.0 works fine, 1.1.14 fails with "No such file or directory".
