### ISSUE TITLE
Install fails on Redhat Linux

### ISSUE THREAD

**Issue by landym** [02strich/pykerberos#28]
I am attempting to do a pip install and I am getting a gcc error. I am running on redhat linux. Apparently gcc does not know that GSS_DLLIMP is defined and/or it is defined as empty.
In file included from src/kerberosbasic.h:18:0, from src/kerberos.c:19:
/usr/include/gssapi/gssapi_generic.h:50:12: error: expected '=', ',', ';', 'asm' or 'attribute' before 'extern'
GSS_DLLIMP extern gss_OID gss_nt_user_name;
I cannot figure out if this is a version of Kerberos (5), the krb5-devel package, or something else in the environment. Any suggestions would be appreciated

**Comment by 02strich** [comment]
Hey, what version of RedHat Linux are you running?

**Comment by landym** [comment]
Redhat V6
2.6.32-358.23.2.el6.x86_64

**Comment by 02strich** [comment]
I have just setup a CentOS6 VM and am running 2.6.32-696.6.3.el6.x86_64. I can pip install pykerberos without an error message. Can you please provide the versions of krb5-devel and the full trace of `pip install pykerberos -vv`?
