### ISSUE TITLE
No package author or homepage in PyPi

### ISSUE THREAD

**Issue by mcassaniti** [02strich/pykerberos#38]
It took me far too long to determine the current source code for this module and who the latest author was. Could this information please be added?

**Comment by 02strich** [comment]
I have added the github link as homepage so it will be picked up as part of the next release. I am not sure whom to set at the author at this point, as this code has gone through many hands.

**Comment by 02strich** [comment]
I would love to merge this back, but do not have the time at this point to work on it :( #17 had some discussion about it, but sadly not a lot has happened since.
