### ISSUE TITLE
Two memory leaks in authenticate_gss_server_step

### ISSUE THREAD

**Issue by cperl82** [02strich/pykerberos#9]
For reference, I'm looking at the code as of commit fbfc8254b4775a05a6d046cea04fdbdcf66c4ce9.

In `authenticate_gss_server_step`, there are two small leaks.  Both occur when `state->server_creds == GSS_C_NO_CREDENTIAL` (line 766).

First, `target_name` is used with `gss_inquire_context` and then with `gss_display_name` on line 776, but the storage allocated for it from the `gss_inquire_context` is never freed with `gss_release_name`.

Second, storage is allocated for `output_token` via the call to `gss_display_name` on line 754.  That is fine, but when `state->server_creds == GSS_C_NO_CREDENTIAL`, `output_token` is reused at line 776 in another call to `gss_display_name` without first having been freed with `gss_release_buffer`.

**Comment by cperl82** [comment]
To be honest, I'm not entirely sure of the relationship between your project, bgamble's pykerberos and the PyKerberos from http://calendarserver.org/, but all three seem to have the same issue (I'm actually using PyKerberos 1.1.1).  This seemed like the place with the most active development, so I submitted the bug report here.

**Comment by 02strich** [comment]
Could you have a look at https://github.com/02strich/pykerberos/commit/7c1d82d9cb79daf5ae6a648e19c5589324ddc6a7 ?

On the question of which ones is the best one: the calendarserver one is the original, but when I started working on this, bgamble's already had some fixes so I started from there. calendarserver just recently resumed activity.

**Comment by cperl82** [comment]
Looks like that'll work to me.

**Comment by cperl82** [comment]
Actually, I just submitted a pull request to move the release inside the if block, as that seems cleaner, as you already have the release of `output_token` via the `end:` label and only need to release it if you're going to reuse it inside the if.

**Comment by 02strich** [comment]
Thanks for the pull request. I have integrated the fixes and your change into v1.1.9
